from __future__ import annotations


VAL_MISSING_REQUIRED = "VAL_MISSING_REQUIRED"
VAL_TYPE_MISMATCH = "VAL_TYPE_MISMATCH"
VAL_ENUM_INVALID = "VAL_ENUM_INVALID"
VAL_RANGE_VIOLATION = "VAL_RANGE_VIOLATION"
VAL_PATTERN_MISMATCH = "VAL_PATTERN_MISMATCH"
VAL_KEY_UNKNOWN = "VAL_KEY_UNKNOWN"
VAL_ALIAS_UNDECLARED = "VAL_ALIAS_UNDECLARED"
VAL_DEPRECATED_FIELD = "VAL_DEPRECATED_FIELD"
VAL_CROSS_RULE = "VAL_CROSS_RULE"


def map_pydantic_error(err):
    raise NotImplementedError("Not Implemented")
