server:
  debug: false
  port: 8080
  observability:
    metrics_enabled: true
    prometheus_path: /metrics
    otel:
      enabled: false
  admin:
    enabled: true
    allow_upload: true
  graphql:
    enabled: false
  sinks:
    enabled: true
  dlq:
    enabled: false
    storage_path: ./.dlq
    simulate_exactly_once: false
